version: '3.4'

services:
  postgres:
    image: "postgres"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: AutosDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=AutosDB;Username=postgres;Password=Carlos18@2024
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
