# Dockerfile
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS aux
WORKDIR webapp
EXPOSE 80

#COPIAMOS ARCHIVOS

COPY ./*.csproj ./
RUN dotnet restore #validamos que contega todos los paguetes

COPY . .
RUN dotnet publish -c Release -o salida

#construimos imagen

FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR webapp
COPY --from=aux /webapp/salida .
ENTRYPOINT ["dotnet", "ASSA.dll"]
